name: Run Main to parse yaml as csv for all T20 Cricket data

on:
  schedule:
  # Runs at 00:00 and 12:00 UTC every day.
    - cron: '0 1/12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Installing Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Executing Main Script
        run: python3 main.py
        
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update all league data" -a

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
    
